### ISSUE TITLE
Shift Button

### ISSUE THREAD

**Issue by HenryNugraha** [lestcape/Sticky-Notes#21]
I'm on Linux Mint 17.1 (Cinnamon 2.4.5). Had no problem typing text into the note, not until I pressed shift button. I need to press the key twice for it to input (i.e., when i typed shift+a+a, it only input A instead of AA).

**Comment by lestcape** [comment]
Hi.
Thanks for take the time: https://github.com/lestcape/Sticky-Notes/issues/20
This is fixed in the last cinnamon unstable.

**Comment by HenryNugraha** [comment]
Sorry for not looking at closed issues.
I've upgraded to latest cinnamon unstable (version 2.4.6, that is) and has confirmed it's now working. Thanks!

**Comment by lestcape** [comment]
Not matter, the thanks to @mtwebster he was who solved this.
regards.
