### ISSUE TITLE
Issue with Shift

### ISSUE THREAD

**Issue by kuraga** [lestcape/Sticky-Notes#25]
Good day!

First time I type a letter after hitting Shift - nothing happens. Only when I continue hitting Shift and then type a letter (the same or not) - the (capitalized) letter appears.

**Comment by lestcape** [comment]
Hi.

This is a problem of cinnamon components and was resolved by @mtwebster in a relatively new release of cinnamon.

https://github.com/linuxmint/muffin/commit/f63fcd0905f50fab14f29e21af42b92688dadfb3

Regard.

**Comment by kuraga** [comment]
Thanks!
