### ISSUE TITLE
extra ":" character in the file "settings-schema.json"->"header appearance"->"description"

### ISSUE THREAD

**Issue by andreevlex** [lestcape/Sticky-Notes#31]
"Appearance:"
Not working translations, as in files `*po` are without the ":" character

**Comment by lestcape** [comment]
I will see what happens later. Anyway, this is for Cinnamon 3.2. Thanks.

**Comment by lestcape** [comment]
Was fixed: https://github.com/lestcape/Sticky-Notes/commit/9d697994ee592acaacb2e7a18e573244c6c8f566

Thanks.
