### ISSUE TITLE
Interrupt moving a note leaves a rectangle behind

### ISSUE THREAD

**Issue by sphh** [lestcape/Sticky-Notes#32]
I accidentally moved a note by grabbing it with the main mouse button. When I noticed I quickly pressed the ESC key and the dragging stopped (which is good). But a rectangle (in my case a green one) remained on the screen and the only way to get rid of it was to actually move the note.

No idea, if this is related to sticky-notes or generally to cinnamon desklets (it's the only desklet I use).

Thank you for this excellent desklet!

Stephan

**Comment by lestcape** [comment]
This is again cinnamon itself.
