### ISSUE TITLE
Wrong link on spices website

### ISSUE THREAD

**Issue by sphh** [lestcape/Sticky-Notes#33]
On the spices website for Sticky-Notes, the link  `Website: https://github.com/lestcape/Sticky-Notes` points to Drives-Manager and not to Sticky-Notes.

**Comment by lestcape** [comment]
I really don' t care to much the current spice web site... Version there are not updated, but thanks.

**Comment by sphh** [comment]
That is really a pity, because the spices website is first point of call regarding desklets and at least it should point to the right website.

Also the versions should be updated there, because the Settings>Extension manager automatically updates the desklets from there. I know, it's more interesting and satisfying to develop one's program instead of spending time to make it accessible to the user ;-) I have absolutely no idea how difficult it is to update the website and/or put new versions onto the spices website, but I would very much appreciate this service.

Thank you for your kind consideration!

**Comment by lestcape** [comment]
Create a software a distribute it are difference things... Spice web site are not a site where can be shared image, code... Github it's convenient for this task... non of my applets desklets required an installation, only copy and paste it. So i don't thing this is really necessary...

**Comment by lestcape** [comment]
Fixed the link.
