### ISSUE TITLE
Typing Ö puts computer into hibernation.

### ISSUE THREAD

**Issue by mijlandst** [lestcape/Sticky-Notes#34]
Today I tried to type an ö in my sticky notes. Since I'm using US international with dead keys, the key combination I used was [Shift] + ['] for a pending ["] and then [o]. Promptly my computer went into hibernation. I repeated the process and it happened again. This is definitely caused by sticky notes as I repeated the process without the sticky notes in focus and my computer did not hibernate.

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
