### ISSUE TITLE
Can't change font

### ISSUE THREAD

**Issue by pierreporte** [lestcape/Sticky-Notes#8]
Hi,

I decided to chose something more “handwritten” in the “Font family” list, but nothing changes (there is always the default typeface), even after closing the configuration window or restarting Cinnamon.

I use Cinnamon 2.0.14 on Archlinux.

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
